use_frameworks!

platform :ios, '8.0'

target 'MHCollectionViewFlowLayout_Example' do
  pod 'MHCollectionViewFlowLayout', :path => '../'

  target 'MHCollectionViewFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
